import { GrantEditor } from "../(agents)/generate-grant/components/GrantEditor";
export default function Simple() {
    const data = {
        "Cover Letter": "Dear [Funder Name],<br/>\n\nOn behalf of HopeBridge Foundation, I am writing to request your support for our \"Digital Literacy for Rural Youth\" initiative. Since 2018, our organization has served over 15,000 underserved students across Karnataka, providing technology education and career readiness programs.\n\nWe are seeking $125,000 to establish three community technology centers in rural districts where 68% of youth lack basic computer skills, severely limiting their employment opportunities. This project will directly serve 900 students annually, offering certified training in digital skills, coding, and online safety.\n\nYour foundation's commitment to educational equity aligns perfectly with our mission. Enclosed please find our complete proposal including executive summary, detailed project plan, and budget breakdown.\n\nThank you for considering this partnership opportunity.\n\nSincerely,\n[Sender Name]\nExecutive Director\nENCLOSURE",
        "Executive Summary": "HopeBridge Foundation proposes the Digital Literacy for Rural Youth project to address the critical technology gap affecting 68% of rural youth in Karnataka's underserved districts. Our organization has a proven track record of serving 15,000+ students since 2018 through innovative education programs.\n\nThis initiative will establish three community technology centers, providing certified digital skills training to 900 students annually. The program includes 120 hours of instruction per student, covering computer fundamentals, productivity software, basic coding, and internet safety.\n\nWe request $125,000 over 18 months to cover equipment, instructor salaries, and operational costs. This investment will increase participants' employability by 45% and create a sustainable model through community partnerships and local government support. Our unique approach combines hands-on learning with mentorship from industry professionals, ensuring measurable outcomes and long-term impact.",
        "Statement Of Need": "Recent Karnataka state education data reveals that 68% of rural youth aged 15-24 lack basic computer literacy skills, compared to just 12% in urban areas [web:7]. This digital divide creates a severe employment barrier, with rural youth unemployment rates reaching 23% versus 8% in cities.\n\nCurrent government initiatives have established only 12 computer centers across the entire region, serving less than 5% of the target population. Existing programs focus primarily on urban areas, leaving 87,000 rural youth without access to technology education.\n\nWe propose to address this gap by establishing three strategically located community centers in Mandya, Hassan, and Chikkamagaluru districts. Each center will serve 300 students annually, providing certified training that aligns with National Digital Literacy Mission standards. This intervention will directly impact 900 youth per year, reducing the skills gap and increasing employability in the growing digital economy.",
        "Project Description": "The Digital Literacy for Rural Youth project will establish three community technology centers in Mandya, Hassan, and Chikkamagaluru districts over 18 months.\n\n**Objectives:**\n- Construct and operationalize three fully-equipped computer labs by Q2 2026\n- Train 900 rural youth in digital literacy and basic coding\n- Achieve 85% certification rate among participants\n- Increase employability metrics by 45% within 6 months of completion\n\n**Activities:**\n- Month 1-3: Site selection, community mobilization, and infrastructure setup\n- Month 4-15: Deliver 120-hour training programs in 6 cohorts per center\n- Month 16-18: Certification, job placement support, and program evaluation\n\n**Methodology:** Interactive curriculum combining instructor-led sessions, hands-on practice, and peer learning. Each center will have 20 computers, high-speed internet, and trained instructors. Partnerships with local schools and panchayats ensure participant recruitment and sustainability.",
        "Organization Background": "HopeBridge Foundation, established in 2015, is a registered nonprofit dedicated to bridging educational gaps for underserved communities in Karnataka. Our mission is to empower youth through technology education and skill development.\n\n**Key Achievements:**\n- Served 15,000+ students across 45 schools since 2018\n- Established 8 successful after-school programs in Bangalore rural district\n- Achieved 92% student retention rate and 78% job placement rate for graduates\n- Received Karnataka State Education Excellence Award in 2022\n\n**Team Expertise:** Our 12-member team includes certified educators, technology specialists, and community development professionals. Executive Director [Sender Name] holds 15 years of nonprofit management experience, while Program Director Dr. Priya Sharma brings PhD-level expertise in educational technology.\n\n**Infrastructure:** We operate a central training facility in Bangalore and maintain partnerships with 25 schools, 3 technical colleges, and local government education departments.",
        "Evaluation Plan": "**Evaluation Questions:**\n1. To what extent did participants improve digital literacy skills?\n2. What percentage of graduates secured employment or advanced education?\n3. How effective were community partnerships in program sustainability?\n\n**Data Collection Methods:**\n- Pre/post skill assessments using National Digital Literacy Mission rubrics\n- Quarterly employment tracking surveys\n- Monthly attendance and engagement metrics\n- Stakeholder interviews with participants, parents, and employers\n\n**Metrics & Targets:**\n- 85% certification completion rate\n- 45% increase in employability within 6 months\n- 90% participant satisfaction score\n- 75% of centers achieve financial sustainability by month 18\n\n**Analysis:** Descriptive statistics for quantitative data, content analysis for qualitative feedback. External evaluator will conduct mid-term and final assessments to ensure objectivity.",
        "Budget Section": "<table><thead><tr><th>Budget Category</th><th>Description</th><th>Amount (USD)</th></tr></thead><tbody><tr><td rowspan=\"4\"><strong>Personnel Costs</strong></td><td>Program Director (0.5 FTE)</td><td>$24,000</td></tr><tr><td>Three Center Coordinators (1.0 FTE each)</td><td>$36,000</td></tr><tr><td>Trainers (part-time)</td><td>$8,000</td></tr><tr><td><strong>Subtotal Personnel</strong></td><td><strong>$68,000</strong></td></tr><tr><td rowspan=\"4\"><strong>Equipment &amp; Infrastructure</strong></td><td>60 computers @ $400 each</td><td>$24,000</td></tr><tr><td>Networking equipment and software</td><td>$5,000</td></tr><tr><td>Furniture and setup</td><td>$3,000</td></tr><tr><td><strong>Subtotal Equipment</strong></td><td><strong>$32,000</strong></td></tr><tr><td rowspan=\"5\"><strong>Operations</strong></td><td>Internet connectivity (18 months)</td><td>$6,000</td></tr><tr><td>Utilities and maintenance</td><td>$4,000</td></tr><tr><td>Materials and supplies</td><td>$5,000</td></tr><tr><td>Monitoring and evaluation</td><td>$3,000</td></tr><tr><td><strong>Subtotal Operations</strong></td><td><strong>$18,000</strong></td></tr><tr><td colspan=\"2\"><strong>Administrative Costs (10%)</strong></td><td><strong>$7,000</strong></td></tr><tr><td colspan=\"2\"><strong>TOTAL FUNDING REQUEST</strong></td><td><strong>$125,000</strong></td></tr></tbody></table><p><strong>Cost per beneficiary:</strong> $139 per student for 120 hours of training</p>",
        "Sustainibility Plan": "**Financial Sustainability Strategy:**\n- Year 2: Secure 40% funding from local government skill development programs\n- Year 3: Generate 25% revenue through nominal student fees ($10 per course) and corporate training partnerships\n- Establish a social enterprise model offering paid digital services to local businesses\n\n**Community Partnerships:**\n- Memoranda of Understanding with district panchayats for infrastructure support\n- Collaboration with Karnataka Skill Development Corporation for certification and funding\n- Engagement with local banks for micro-loan programs for graduates starting digital businesses\n\n**Capacity Building:**\n- Train local youth as peer educators and center managers\n- Develop volunteer network of IT professionals for mentorship\n- Create alumni association for ongoing support and networking\n\n**Long-term Vision:** Transition to self-sustaining community-managed centers by Year 4, with HopeBridge providing technical support and quality assurance.",
        "new_section": "This section can be customized for additional requirements such as risk management plan, stakeholder engagement strategy, or technology infrastructure details based on specific funder guidelines.",
        "Funders Name": "Global Education Impact Foundation",
        "Senders Name": "Dr. Rajesh Kumar",
        "Project Title": "Digital Literacy for Rural Youth: Bridging Karnataka's Digital Divide"
    }
    return (
        <div>
            <GrantEditor grant={data} />
        </div>
    )

}